### ISSUE TITLE
Examining an event

### ISSUE THREAD

**Issue by szepeviktor** [munin-monitoring/munin#297]
When trying to find the cause and attributes of (e.g.) an attack a guideline would be helpful:

```css
#content {
    position: relative;
}
#content:after {
    border-right: 1px solid black;
    bottom: 0;
    content: "";
    left: 364px;
    position: absolute;
    top: 0;
}
```
And `left` would be set by Javascript to a point of time as in dynazoom: `2014-11-08T13:25:48+0100`
